In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Boris', 'Eugene'],
    'Age': [25, 30, 35, 16, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'Miami']
}
df = pd.DataFrame(data)

In [5]:
mask = (df['Age'] > 20) & (df['City'] != 'Miami')
df[mask]

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [11]:
filtered_df = df[df['Age'].between(20, 35)]
filtered_df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago