In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Boris', 'Eugene'],
    'Age': [25, None, 35, 16, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', None, 'Miami']
}
df = pd.DataFrame(data)

In [2]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False   True
4  False  False  False

In [3]:
df_cleared = df.dropna()
df_cleared

      Name   Age      City
0    Alice  25.0  New York
2  Charlie  35.0   Chicago
4   Eugene  45.0     Miami

In [4]:
df_dropped_axis = df.dropna(axis=1)
df_dropped_axis

      Name
0    Alice
1      Bob
2  Charlie
3    Boris
4   Eugene

In [11]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['City'] = df['City'].fillna('Unknown')
df

      Name   Age         City
0    Alice  25.0     New York
1      Bob  10.0  Los Angeles
2  Charlie  35.0      Chicago
3    Boris  16.0      Unknown
4   Eugene  45.0        Miami