In [11]:
import pandas as pd

sales_data = {
    'Region': ['North', 'South', 'North', 'South', 'East', 'North'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'C'],
    'Sales': [100, 80, 120, 90, 70, 110],
    'OrderDate': ['2024-01-05', '2024-01-07', '2024-01-10', '2024-02-02', '2024-02-05', '2024-02-09'],
}
df = pd.DataFrame(sales_data)

In [12]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df

  Region Product  Sales  OrderDate
0  North       A    100 2024-01-05
1  South       A     80 2024-01-07
2  North       B    120 2024-01-10
3  South       B     90 2024-02-02
4   East       A     70 2024-02-05
5  North       C    110 2024-02-09

In [13]:
df.set_index('OrderDate', inplace=True)
df

           Region Product  Sales
OrderDate
2024-01-05  North       A    100
2024-01-07  South       A     80
2024-01-10  North       B    120
2024-02-02  South       B     90
2024-02-05   East       A     70
2024-02-09  North       C    110

In [15]:
df['Year'] = df.index.year
df['Month'] = df.index.month
df['Day'] = df.index.day
df

           Region Product  Sales  Year  Month  Day
OrderDate
2024-01-05  North       A    100  2024      1    5
2024-01-07  South       A     80  2024      1    7
2024-01-10  North       B    120  2024      1   10
2024-02-02  South       B     90  2024      2    2
2024-02-05   East       A     70  2024      2    5
2024-02-09  North       C    110  2024      2    9

In [16]:
weekly_sales = df['Sales'].resample('W').sum()
weekly_sales

OrderDate
2024-01-07    180
2024-01-14    120
2024-01-21      0
2024-01-28      0
2024-02-04     90
2024-02-11    180
Freq: W-SUN, Name: Sales, dtype: int64