In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Boris'],
    'Age': [25, 30, 35, 16],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Boston']
}
df = pd.DataFrame(data)

In [15]:
row = df.loc[2]['City']
row

'Chicago'

In [16]:
subset_rows = df.loc[1:2, ['Name', 'City']]
subset_rows

      Name         City
1      Bob  Los Angeles
2  Charlie      Chicago

In [38]:
mask = df['Age'] > 20
filtered = df.loc[mask].iloc[0:2,0:2]
filtered

    Name  Age
0  Alice   25
1    Bob   30

In [40]:
df.iloc[1]

Name            Bob
Age              30
City    Los Angeles
Name: 1, dtype: object