In [1]:
import pandas as pd

data = [10, 20, 30, 40]
series = pd.Series(data)
series

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
# print(df)
# print(df.dtypes)
# print('...')
# print(df.describe)

In [10]:
df['Countries'] = ['USA', 'UK', 'Ukraine']
df['Age Group'] = ['Young' if age < 30 else 'Mature' for age in df['Age']]
df

      Name  Age         City Countries Age Group
0    Alice   25     New York       USA     Young
1      Bob   30  Los Angeles        UK    Mature
2  Charlie   35      Chicago   Ukraine    Mature

In [11]:
# Drop
df = df.drop('Age Group', axis=1) 
df

      Name  Age         City Countries
0    Alice   25     New York       USA
1      Bob   30  Los Angeles        UK
2  Charlie   35      Chicago   Ukraine

In [14]:
df_copy = df.copy()
df_copy

      Name  Age         City Countries
0    Alice   25     New York       USA
1      Bob   30  Los Angeles        UK
2  Charlie   35      Chicago   Ukraine

In [17]:
# add columns
df_copy = df_copy.assign(Discount=[5, 10, 15], Total_Spend=[100, 150, 200])
df_copy

      Name  Age         City Countries  Discount  Total_Spend
0    Alice   25     New York       USA         5          100
1      Bob   30  Los Angeles        UK        10          150
2  Charlie   35      Chicago   Ukraine        15          200