In [2]:
import pandas as pd

sales_data = {
    'Region': ['North', 'South', 'North', 'South', 'East', 'North'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'C'],
    'Sales': [100, 80, 120, 90, 70, 110],
    'Month': ['Jan', 'Jan', 'Jan', 'Feb', 'Feb', 'Feb']
}
df = pd.DataFrame(sales_data)

In [15]:
grouped = df.groupby('Month').apply(lambda x: x)
grouped

        Region Product  Sales
Month
Feb   3  South       B     90
      4   East       A     70
      5  North       C    110
Jan   0  North       A    100
      1  South       A     80
      2  North       B    120

In [13]:
grouped = df.groupby('Region')['Sales'].max()
grouped

Region
East      70
North    120
South     90
Name: Sales, dtype: int64

In [14]:
grouped = df.groupby(['Region', 'Product'])['Sales'].sum()
grouped

Region  Product
East    A           70
North   A          100
        B          120
        C          110
South   A           80
        B           90
Name: Sales, dtype: int64

In [ ]:
grouped = df.groupby(['Region', 'Product'])['Sales'].agg(['sum', 'mean', 'count'])
grouped

                sum   mean  count
Region Product
East   A         70   70.0      1
North  A        100  100.0      1
       B        120  120.0      1
       C        110  110.0      1
South  A         80   80.0      1
       B         90   90.0      1