In [2]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Boris', 'Eugene'],
    'Age': [25, 30, 35, 16, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'Miami']
}
df = pd.DataFrame(data)

In [6]:
sorted_df = df.sort_values(by=['City', 'Age'], ascending=False)
sorted_df

      Name  Age         City
0    Alice   25     New York
4   Eugene   45        Miami
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Boris   16       Boston

In [8]:
sorted_index = sorted_df.sort_index()
sorted_index

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Boris   16       Boston
4   Eugene   45        Miami